controllers_security:
    resource: ../src/Controller/LoginController.php
    type: attribute

controllers_register:
    resource: ../src/Controller/RegistrationController.php
    type: attribute

controllers_resetPassword:
    resource: ../src/Controller/ResetPasswordController.php
    type: attribute

controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix:  front


controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix:  back_admin
    prefix: /admin