security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: 'y'  # Replace with the actual property used for admin usernames

        app_user_provider:
            entity:
                class: App\Entity\User
                property: 'username'  # Replace with the actual property used for user usernames

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            lazy: true
            provider: app_admin_provider
            custom_authenticator:
                - App\Security\AdminAuthenticator
            entry_point: App\Security\AdminAuthenticator
            logout:
                path: app_logout_admin
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /admin
                always_remember_me: true
            access_control:
                 - { path: ^/admin, roles: ROLE_ADMIN }
                 - { path: ^/user, roles: ROLE_USER }

        user:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Login\UserAuthenticator
            entry_point: App\Login\UserAuthenticator
            logout:
                path: app_logout_user
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /user
                always_remember_me: true
            access_control:
                - { path: ^/user, roles: ROLE_USER }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }

    when@test:
        security:
            password_hashers:
                Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                    algorithm: auto
                    cost: 4
                    time_cost: 3
                    memory_cost: 10
